#!/bin/bash

# go to root directory of git repo:
_rdir=`git rev-parse --show-toplevel`
cd $_rdir

# make sure base.nes and working.nes exist:
if [ ! -f ./base.nes ]
then
  >&2 echo "Base ROM (base.nes) is not found! Aborting commit."
  exit 1;
fi

if [ ! -f ./base.nes ]
then
  >&2 echo "Modified ROM (working.nes) is not found! Aborting commit."
  >&2 echo "(Did you ever generate working.nes with apply.sh?)"
  exit 2;
fi

# generate patch
./make-patch.sh

# pause to read input if successful:
if [ $? -eq 0 ]
then
  sleep 0.5
fi

exit $?
